// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArHVpXjnEJhBI13--a3aujJ-3zX6GoipU',
    appId: '1:553717185036:web:a8bb675783e2147c73cc29',
    messagingSenderId: '553717185036',
    projectId: 'flutterproject-ae9ad',
    authDomain: 'flutterproject-ae9ad.firebaseapp.com',
    storageBucket: 'flutterproject-ae9ad.firebasestorage.app',
    measurementId: 'G-Z1WRXSHE8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHEQNCzAaGto_ETRkPBWkL5Vm848HrgRg',
    appId: '1:553717185036:android:0663107e8c0eb1cb73cc29',
    messagingSenderId: '553717185036',
    projectId: 'flutterproject-ae9ad',
    storageBucket: 'flutterproject-ae9ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr4AvdKr2xm7haL4r-L7jqLYqoJk4q_94',
    appId: '1:553717185036:ios:91829fc9728bb66e73cc29',
    messagingSenderId: '553717185036',
    projectId: 'flutterproject-ae9ad',
    storageBucket: 'flutterproject-ae9ad.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr4AvdKr2xm7haL4r-L7jqLYqoJk4q_94',
    appId: '1:553717185036:ios:91829fc9728bb66e73cc29',
    messagingSenderId: '553717185036',
    projectId: 'flutterproject-ae9ad',
    storageBucket: 'flutterproject-ae9ad.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArHVpXjnEJhBI13--a3aujJ-3zX6GoipU',
    appId: '1:553717185036:web:8b3c767ece8ef64173cc29',
    messagingSenderId: '553717185036',
    projectId: 'flutterproject-ae9ad',
    authDomain: 'flutterproject-ae9ad.firebaseapp.com',
    storageBucket: 'flutterproject-ae9ad.firebasestorage.app',
    measurementId: 'G-TP20Z9P1P8',
  );
}
